name = "vagudle"
compatibility_date = "2026-05-14"
pages_build_output_dir = "dist"

[vars]
FIREBASE_PROJECT_ID = "vagudle"

[[d1_databases]]
binding = "DB"
database_name = "vagudle-duels"
database_id = "e32fb5db-fd30-498a-a8b9-46c2c0103489"

[[kv_namespaces]]
binding = "FEEDBACK_KV"
id = "331edf8aaa9e445ba3784228b101cd04"