name = "vagudle-worker"
main = "src/index.js"
compatibility_date = "2026-09-08"
preview_urls = false

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["15 8 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "vagudle-data"
database_id = "035d8b7e-e796-467a-8c7c-29a0230d4f6c"

[[durable_objects.bindings]]
name = "SYNC_ROOM"
class_name = "SyncRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncRoom"]
